export const prompts = []

const addPrompt = (prompt) => {
  prompts.push(prompt)
}

addPrompt("What do you want to be remembered for?")
addPrompt("What is the most important lesson you’ve learned in life?")
addPrompt("If you could change one thing about the world, what would it be?")
addPrompt("What are you most grateful for?")
addPrompt("What is a dream you have yet to achieve?")
addPrompt("What are some of your core values?")
addPrompt("What does success mean to you?")
addPrompt("How do you handle stress and pressure?")
addPrompt("What is a defining moment in your life?")
addPrompt("What role does family play in your life?")
addPrompt("What are you most proud of?")
addPrompt("Who has been the most influential person in your life?")
addPrompt("What are you passionate about?")
addPrompt("What are your biggest fears?")
addPrompt("What does happiness look like for you?")
addPrompt("What is your strongest childhood memory?")
addPrompt("How do you define love?")
addPrompt("What’s a risk you took that paid off?")
addPrompt("What’s a belief you hold strongly?")
addPrompt("What is a cause you deeply care about?")
addPrompt("What’s something you’ve learned from failure?")
addPrompt("What’s one thing you wish you knew sooner in life?")
addPrompt("What’s the best advice you’ve ever received?")
addPrompt("What’s a hobby or activity that brings you joy?")
addPrompt("How do you stay motivated during tough times?")
addPrompt("What are some goals you’re currently working towards?")
addPrompt("What’s your favorite way to spend a weekend?")
addPrompt("How do you practice self-care?")
addPrompt("What’s a book or movie that has deeply influenced you?")
addPrompt("If you could have dinner with anyone, living or dead, who would it be and why?")
addPrompt("What does your perfect day look like?")
addPrompt("If you could live anywhere in the world, where would it be and why?")
addPrompt("What is a decision you made that changed your life forever?")
addPrompt("How do you measure success in your life?")
addPrompt("What’s something you’ve always wanted to try but haven’t yet?")
addPrompt("What is your biggest regret?")
addPrompt("What motivates you to get out of bed every morning?")
addPrompt("If you had unlimited resources, what project would you undertake?")
addPrompt("What role does spirituality play in your life?")
addPrompt("What’s the most challenging experience you’ve faced and how did you overcome it?")
addPrompt("How do you define friendship?")
addPrompt("What’s a piece of advice you’d give to your younger self?")
addPrompt("What’s your favorite memory from childhood?")
addPrompt("How do you handle conflict in relationships?")
addPrompt("What’s a misconception people often have about you?")
addPrompt("What’s an experience that made you stronger?")
addPrompt("What are your top three priorities in life?")
addPrompt("What’s your proudest accomplishment?")
addPrompt("What do you value most in a partner?")
addPrompt("How do you cope with disappointment?")
addPrompt("What is your biggest dream for the future?")
addPrompt("What is something you’ve learned about yourself recently?")
addPrompt("What’s a habit you’d like to break?")
addPrompt("What’s the most beautiful place you’ve ever been to?")
addPrompt("What’s your greatest strength?")
addPrompt("What’s your biggest weakness?")
addPrompt("How do you express gratitude in your daily life?")
addPrompt("What’s a lesson you’ve learned from a difficult relationship?")
addPrompt("What do you admire most about your best friend?")
addPrompt("What’s your philosophy on life?")
addPrompt("What’s the most important promise you’ve ever made?")
addPrompt("What’s a skill you wish you had?")
addPrompt("What’s the best gift you’ve ever received?")
addPrompt("What’s a mistake you made that taught you something valuable?")
addPrompt("How do you define integrity?")
addPrompt("What’s your biggest fear and why?")
addPrompt("What’s a goal you achieved that you’re particularly proud of?")
addPrompt("What’s the best compliment you’ve ever received?")
addPrompt("What’s your favorite way to relax?")
addPrompt("What’s something you want to be remembered for?")
addPrompt("What’s a tradition that’s important to you?")
addPrompt("How do you show love to others?")
addPrompt("What’s a challenge you’re currently facing?")
addPrompt("What’s the most adventurous thing you’ve ever done?")
addPrompt("What’s your definition of happiness?")
addPrompt("How do you stay true to yourself?")
addPrompt("What’s a passion you’d like to pursue more deeply?")
addPrompt("What’s something you wish you could do over?")
addPrompt("What’s a book that has changed your perspective?")
addPrompt("What’s your favorite family memory?")
addPrompt("How do you deal with change?")
addPrompt("What’s a dream you have that you haven’t shared with many people?")
addPrompt("What’s your favorite way to give back to the community?")
addPrompt("What’s something you’ve learned from a recent experience?")
addPrompt("How do you handle failure?")
addPrompt("What’s the most thoughtful thing someone has done for you?")
addPrompt("What’s your biggest hope for the future?")
addPrompt("What’s something that always makes you smile?")
addPrompt("What’s a lesson you’ve learned from a stranger?")
addPrompt("How do you find balance in your life?")
addPrompt("What’s your favorite thing about yourself?")
addPrompt("What’s a risk you regret not taking?")
addPrompt("What’s the best advice you’ve ever given?")
addPrompt("What’s a cause you’re passionate about?")
addPrompt("What’s a song that has a lot of meaning to you?")
addPrompt("What’s the most spontaneous thing you’ve ever done?")
addPrompt("What’s a belief you used to hold that you’ve changed your mind about?")
addPrompt("How do you want to impact the world?")
addPrompt("What’s a goal you’re currently working towards?")
addPrompt("What’s something you’re thankful for today?")
